apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: msvc-${SERVICE_NAME}-redis
spec:
  ports:
  - port: 6379
    name: server
  - port: 26379
    name: sentinel
  clusterIP: None
  selector:
    k8s-app: msvc-${SERVICE_NAME}-redis
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: msvc-${SERVICE_NAME}-redis
spec:
  replicas: 3
  template:
    metadata:
      labels:
        k8s-app: msvc-${SERVICE_NAME}-redis
    spec:
      containers:
        - name: server
          image: sadminriley/k8s-ha-redis-server:4.0.10
          env:
          - name: SRV_NAME
            value: msvc-${SERVICE_NAME}-redis
          - name: REDIS_DATA_DIR
            value: /data
          - name: REDIS_BIND_ADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.podIP

          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
          ports:
            - name: redis
              containerPort: 6379
              protocol: "TCP"

        - name: sentinel
          image: sadminriley/k8s-ha-redis-sentinel:4.0.10
          env:
          - name: SRV_NAME
            value: msvc-${SERVICE_NAME}-redis
          - name: REDIS_MASTER_NAME
            value: ha-master
          - name: SENTINEL_QUORUM
            value: "2"
          - name: SENTINEL_BIND_ADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
          ports:
            - name: sentinel
              containerPort: 26379
              protocol: "TCP"
